name: Android

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        demo:
          - demo-01_checkxr
          - demo-02_displayxr
          - demo-03_passthroughxr
          - demo-04_handtrackingxr
          - demo-05_inputxr
          - demo-06_interactionsxr
        
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        
      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r25c
          
      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: android-${{ matrix.demo }}
          
      - name: Create dummy keystore properties
        run: |
          echo "SIGNING_KEY_ALIAS=debug" > keystore.properties
          echo "SIGNING_KEY_PASSWORD=android" >> keystore.properties
          echo "SIGNING_KEYSTORE_FILE=$ANDROID_HOME/debug.keystore" >> keystore.properties
          echo "SIGNING_KEYSTORE_PASSWORD=android" >> keystore.properties

      - name: Make Gradle wrapper executable
        run: |
          chmod +x ${{ github.workspace }}/${{ matrix.demo }}/android/gradlew

      - name: Build Android APK for ${{ matrix.demo }}
        working-directory: ${{ github.workspace }}/${{ matrix.demo }}/android
        run: |
          cp ${{ github.workspace }}/keystore.properties ./
          ./gradlew assembleDebug
        env:
          CMAKE_C_COMPILER_LAUNCHER: ccache
          CMAKE_CXX_COMPILER_LAUNCHER: ccache
          ANDROID_SDK_ROOT: ${{ env.ANDROID_SDK_ROOT }}
